name: deploy
on:
  workflow_run:
    workflows: [ Build ]
    branches: [ main ]
    types:
      - completed

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/levant:latest
      volumes:
        - ${{ github.workspace }}:/app
      env:
        NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run plan
        run: plan /app/nomad/cosmos-movie-service.nomad

      - name: Run deploy
        run: deploy /app/nomad/cosmos-movie-service.nomad