name: Maven
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build
        run: mvn -s $GITHUB_WORKSPACE/settings.xml -B -f pom.xml verify
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: mvn -s $GITHUB_WORKSPACE/settings.xml -Dmaven.test.skip deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
